# ============================================================
# SEC-OPS LAB - Ansible Inventory
# ============================================================
# All targets are reached exclusively via SSH.
# ============================================================

# ----- Android / Termux Devices -----
[phones]
mine ansible_host=192.168.1.31
hanane ansible_host=192.168.1.32

# ----- Linux Servers -----
[linux_servers]
ubuntu_srv ansible_host=192.168.8.200

# ----- Windows Machines (Win32-OpenSSH) -----
[windows_machines]
win_test ansible_host=192.168.1.194

# win_srv_2019  ansible_host=192.168.8.194
# win_client_10 ansible_host=192.168.8.180