# ============================================================
# SEC-OPS LAB - Ansible Inventory (FINAL)
# ============================================================

# ============================================================
# Android / Termux Devices (SSH)
# ============================================================
#[phones]
#mine ansible_host=192.168.1.31 ansible_connection=ssh
#hanane ansible_host=192.168.1.32 ansible_connection=ssh

#[phones:vars]
#ansible_user=termux_user
#ansible_ssh_private_key_file=~/.ssh/id_rsa

# ============================================================
# Windows Machines (WinRM)
# ============================================================


[windows_machines]
#win_test ansible_host=192.168.1.194
# win_srv_2019 ansible_host=192.168.1.14
win_client_10 ansible_host=192.168.1.27

# ============================================================
# Linux Servers (SSH)
# ============================================================
[linux_servers]
ubuntu_srv ansible_host=192.168.1.16 ansible_connection=ssh

[linux_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa




[windows_machines:vars]
ansible_user=ansible
ansible_password=azerty@123
ansible_connection=ssh
ansible_shell_type=powershell
ansible_become_method=runas
ansible_port=22
ansible_winrm_server_cert_validation=ignore

# 8.191